version: '2.1'
services:
  database:
    image: postgres:latest
    ports:
      - "54101:5432"
    environment:
      POSTGRES_USER:     "user1"
      POSTGRES_PASSWORD: "user1"
      POSTGRES_DB:       "unjchp6_db"
    networks:
      backend:
        aliases:
          - "unjchp6_db"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5       
networks:
  backend:
    driver: bridge